# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-14 08:45
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FoodEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='created')),
                ('co2_cost', models.FloatField(verbose_name='carbondioxide cost')),
                ('dish_type', models.CharField(choices=[('M', 'Meat'), ('F', 'Fish'), ('V', 'Vegetarian')], max_length=1, verbose_name='dish type')),
                ('image', models.ImageField(upload_to='food_entries/', verbose_name='image')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'food entries',
            },
        ),
        migrations.CreateModel(
            name='TravelEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='created')),
                ('co2_cost', models.FloatField(verbose_name='carbondioxide cost')),
                ('distance_meters', models.FloatField(verbose_name='distance in meters')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'travel entries',
            },
        ),
    ]
