# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-14 11:57
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('zombie', '0002_auto_20180414_1356'),
    ]

    operations = [
        migrations.CreateModel(
            name='AbstractEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='created')),
                ('co2_cost', models.FloatField(verbose_name='carbondioxide cost')),
                ('polymorphic_ctype', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='polymorphic_zombie.abstractentry_set+', to='contenttypes.ContentType')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'manager_inheritance_from_future': True,
            },
        ),
        migrations.RemoveField(
            model_name='foodentry',
            name='co2_cost',
        ),
        migrations.RemoveField(
            model_name='foodentry',
            name='created',
        ),
        migrations.RemoveField(
            model_name='foodentry',
            name='id',
        ),
        migrations.RemoveField(
            model_name='foodentry',
            name='polymorphic_ctype',
        ),
        migrations.RemoveField(
            model_name='foodentry',
            name='user',
        ),
        migrations.RemoveField(
            model_name='travelentry',
            name='co2_cost',
        ),
        migrations.RemoveField(
            model_name='travelentry',
            name='created',
        ),
        migrations.RemoveField(
            model_name='travelentry',
            name='id',
        ),
        migrations.RemoveField(
            model_name='travelentry',
            name='polymorphic_ctype',
        ),
        migrations.RemoveField(
            model_name='travelentry',
            name='user',
        ),
        migrations.AddField(
            model_name='foodentry',
            name='abstractentry_ptr',
            field=models.OneToOneField(auto_created=True, default=None, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='zombie.AbstractEntry'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='travelentry',
            name='abstractentry_ptr',
            field=models.OneToOneField(auto_created=True, default=None, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='zombie.AbstractEntry'),
            preserve_default=False,
        ),
    ]
