# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-14 14:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zombie', '0003_auto_20180414_1357'),
    ]

    operations = [
        migrations.AddField(
            model_name='travelentry',
            name='travel_type',
            field=models.CharField(choices=[('B', 'buss'), ('R', 'tåg'), ('P', 'bil (bensin)'), ('C', 'cykel'), ('W', 'gång')], default='P', max_length=1, verbose_name='travel type'),
            preserve_default=False,
        ),
    ]
