# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-14 22:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zombie', '0006_travelentry_geometry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='abstractentry',
            name='created',
            field=models.DateTimeField(verbose_name='created'),
        ),
        migrations.AlterField(
            model_name='travelentry',
            name='travel_type',
            field=models.CharField(choices=[('B', 'buss'), ('R', 'tåg'), ('P', 'bil (bensin)'), ('C', 'cykel'), ('W', 'gång'), ('F', 'flyg')], max_length=1, verbose_name='travel type'),
        ),
    ]
